### ISSUE TITLE
YouTube Frontend Changed, Extractor Update Required

### ISSUE THREAD

**Issue by MapleWheels** [RSoulwin/NewPipeZing#2]
### Checklist

- [x] I am using the latest version - 0.19.9.5 Jan17 
- [x] I checked, but didn't find any duplicates (open, closed does not apply) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
Many videos and songs, especially those hosted by YouTube's music publishing, will fail to parse.

Sample Links:
https://www.youtube.com/watch?v=UnIhRpIT7nc
https://www.youtube.com/watch?v=VLcpJe-Hv2M
https://www.youtube.com/watch?v=wj95BA8XfuU

### Actual behaviour

Fails to parse page, Guru Meditation error.

### Expected behavior

>_>

### Screenshots/Screen recordings

<

## Exception
* __User Action:__ requested stream
* __Request:__ https://www.youtube.com/watch?v=UnIhRpIT7nc
* __Content Country:__ CA
* __Content Language:__ en-CA
* __App Language:__ en_CA
* __Service:__ YouTube
* __Version:__ 0.19.9.5
* __OS:__ Linux samsung/dm3qcsx/dm3q:14/UP1A.231005.007/S918WVLU2CXCI:user/release-keys 14 - 34
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.stream.StreamInfo$StreamExtractException: Could not get any stream. See error variable to get further details.
	at org.schabi.newpipe.extractor.stream.StreamInfo.extractStreams(StreamInfo.java:188)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:82)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:73)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:123)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$YTHJjScxCJNO1LTCqs3IKy35iyY.call(Unknown Source:4)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.Flowable.subscribe(Flowable.java:14935)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

```
</details>
<hr>

### Device info

 - Android version/Custom ROM version: 14, OneUI 6.1
 - Device model: Samsung S23 Ultra

**Comment by ShareASmile** [comment]
It seems like a cache issue, clearing cache in History and cache in Settings solves it for me.

**Comment by MapleWheels** [comment]
> It seems like a cache issue, clearing cache via History and cache in Settings solves it for me.
> 
> A similar report was there in PipePipe repository which also uses bit old custom extractor. Issue No. 288 in https://github.com/InfinityLoop1308/PipePipe

It appears that A/B rollout/testing made it appear fine but as we now know from the big YT update a couple of weeks back, it was a change.

Anyways, there's a new update to the Extractor that seems to have fixed all playback issues. Any chance we can get an extractor update?

**Comment by RSoulwin** [comment]
You can use the Latest Release from https://github.com/ShareASmile/NewPipeZing/releases/tag/v0.19.9.6
